/**
 * Default seed catalog for Rule-Based Support Assistant.
 * Used until Super Admin publishes content to Firestore.
 */
import {
  DEFAULT_SMART_ASSISTANT_CONTACT,
  buildKeywordsFromAnswers,
  type AssistantAnswer,
  type AssistantCatalog,
  type AssistantCategory,
  type AssistantFlow,
  type SmartAssistantScope,
  type SmartAssistantRule,
} from './smartAssistantEngine';

const ALL: SmartAssistantScope[] = [
  'landing',
  'superadmin',
  'platform_assistant',
  'school_admin',
  'teacher',
  'parent',
  'guard',
  'distributor',
];

const LANDING: SmartAssistantScope[] = ['landing'];
const PARENT: SmartAssistantScope[] = ['parent'];
const TEACHER: SmartAssistantScope[] = ['teacher'];
const ADMIN: SmartAssistantScope[] = ['school_admin'];
const DIST: SmartAssistantScope[] = ['distributor'];
const STAFF: SmartAssistantScope[] = ['school_admin', 'teacher', 'parent', 'guard', 'distributor', 'platform_assistant', 'superadmin'];

export const SEED_CATEGORIES: AssistantCategory[] = [
  { id: 'cat_subscriptions', titleAr: 'الاشتراكات', titleEn: 'Subscriptions', emoji: '💳', order: 10, scopes: LANDING, active: true },
  { id: 'cat_account', titleAr: 'الحساب', titleEn: 'Account', emoji: '👤', order: 20, scopes: STAFF, active: true },
  { id: 'cat_tech', titleAr: 'المشاكل التقنية', titleEn: 'Technical', emoji: '⚙️', order: 30, scopes: ALL, active: true },
  { id: 'cat_school', titleAr: 'إدارة المدرسة', titleEn: 'School admin', emoji: '🏫', order: 40, scopes: ADMIN, active: true },
  { id: 'cat_parent', titleAr: 'ولي الأمر', titleEn: 'Parent', emoji: '👨‍👩‍👧', order: 45, scopes: PARENT, active: true },
  { id: 'cat_teacher', titleAr: 'المعلم', titleEn: 'Teacher', emoji: '📘', order: 46, scopes: TEACHER, active: true },
  { id: 'cat_distributor', titleAr: 'الموزع', titleEn: 'Distributor', emoji: '📦', order: 47, scopes: DIST, active: true },
  { id: 'cat_platform', titleAr: 'عن المنصة', titleEn: 'About', emoji: '✨', order: 5, scopes: LANDING, active: true },
  { id: 'cat_support', titleAr: 'التواصل مع الدعم', titleEn: 'Contact support', emoji: '📞', order: 90, scopes: ALL, active: true },
];

export const SEED_FLOWS: AssistantFlow[] = [
  { id: 'flow_what_is', categoryId: 'cat_platform', titleAr: 'ما هي SchoolixIQ؟', order: 1, scopes: LANDING, active: true },
  { id: 'flow_pricing', categoryId: 'cat_subscriptions', titleAr: 'الأسعار والباقات', order: 1, scopes: LANDING, active: true },
  { id: 'flow_subscribe', categoryId: 'cat_subscriptions', titleAr: 'طريقة الاشتراك', order: 2, scopes: LANDING, active: true },
  { id: 'flow_demo', categoryId: 'cat_platform', titleAr: 'طلب عرض تجريبي', order: 2, scopes: LANDING, active: true },
  { id: 'flow_account_create', categoryId: 'cat_account', titleAr: 'إنشاء حساب', order: 1, scopes: STAFF, active: true },
  { id: 'flow_password', categoryId: 'cat_account', titleAr: 'تغيير كلمة المرور', order: 2, scopes: STAFF, active: true },
  { id: 'flow_profile', categoryId: 'cat_account', titleAr: 'تعديل البيانات', order: 3, scopes: STAFF, active: true },
  { id: 'flow_login_issue', categoryId: 'cat_tech', titleAr: 'مشاكل تسجيل الدخول', order: 1, scopes: ALL, active: true },
  { id: 'flow_app', categoryId: 'cat_tech', titleAr: 'التطبيق والجوال', order: 2, scopes: ALL, active: true },
  { id: 'flow_students', categoryId: 'cat_school', titleAr: 'الطلاب', order: 1, scopes: ADMIN, active: true },
  { id: 'flow_staff', categoryId: 'cat_school', titleAr: 'الموظفين', order: 2, scopes: ADMIN, active: true },
  { id: 'flow_reports', categoryId: 'cat_school', titleAr: 'التقارير', order: 3, scopes: ADMIN, active: true },
  { id: 'flow_absence', categoryId: 'cat_parent', titleAr: 'الغياب', order: 1, scopes: PARENT, active: true },
  { id: 'flow_fees', categoryId: 'cat_parent', titleAr: 'الرسوم', order: 2, scopes: PARENT, active: true },
  { id: 'flow_homework', categoryId: 'cat_parent', titleAr: 'الواجبات', order: 3, scopes: PARENT, active: true },
  { id: 'flow_grades', categoryId: 'cat_teacher', titleAr: 'الدرجات', order: 1, scopes: TEACHER, active: true },
  { id: 'flow_attendance', categoryId: 'cat_teacher', titleAr: 'الحضور', order: 2, scopes: TEACHER, active: true },
  { id: 'flow_schedule', categoryId: 'cat_teacher', titleAr: 'الجدول', order: 3, scopes: TEACHER, active: true },
  { id: 'flow_commission', categoryId: 'cat_distributor', titleAr: 'العمولات', order: 1, scopes: DIST, active: true },
  { id: 'flow_orders', categoryId: 'cat_distributor', titleAr: 'الطلبات', order: 2, scopes: DIST, active: true },
  { id: 'flow_contact', categoryId: 'cat_support', titleAr: 'قنوات التواصل', order: 1, scopes: ALL, active: true },
];

export const SEED_ANSWERS: AssistantAnswer[] = [
  {
    id: 'ans_what_is',
    categoryId: 'cat_platform',
    flowId: 'flow_what_is',
    titleAr: 'تعريف المنصة',
    bodyAr: 'SchoolixIQ منصة سحابية لإدارة المدارس: الحضور، الدرجات، التواصل، التسريح الآمن، والتقارير — بتجربة عربية كاملة.',
    keywords: ['ما هي', 'ما هو', 'المنصة', 'schoolix', 'سكوليكس', 'تعريف'],
    actions: [
      { id: 'a1', type: 'open_section', labelAr: 'استكشف المميزات', value: '#features' },
    ],
    priority: 100,
    order: 1,
    scopes: LANDING,
    active: true,
  },
  {
    id: 'ans_pricing',
    categoryId: 'cat_subscriptions',
    flowId: 'flow_pricing',
    titleAr: 'الباقات',
    bodyAr: 'تجد الباقات والأسعار في قسم الباقات بالصفحة الرئيسية. اختر الخطة المناسبة ثم أكمل طلب الاشتراك.',
    keywords: ['باقات', 'أسعار', 'اشتراك', 'خطة', 'pricing', 'price'],
    actions: [
      { id: 'a1', type: 'open_section', labelAr: 'عرض الباقات', value: '#pricing' },
    ],
    priority: 95,
    order: 1,
    scopes: LANDING,
    active: true,
  },
  {
    id: 'ans_subscribe',
    categoryId: 'cat_subscriptions',
    flowId: 'flow_subscribe',
    titleAr: 'خطوات الاشتراك',
    bodyAr: '1) اضغط "ابدأ الآن"\n2) سجّل عبر Google للتحقق من الهوية\n3) اختر الباقة وأدخل بيانات المدرسة\n4) ينتظر الطلب موافقة السوبر أدمن',
    keywords: ['اشتراك', 'تسجيل مدرسة', 'انضم', 'register', 'signup'],
    actions: [
      { id: 'a1', type: 'open_route', labelAr: 'بدء التسجيل', value: '/register' },
    ],
    priority: 90,
    order: 1,
    scopes: LANDING,
    active: true,
  },
  {
    id: 'ans_demo',
    categoryId: 'cat_platform',
    flowId: 'flow_demo',
    titleAr: 'عرض تجريبي',
    bodyAr: 'اطلب عرضاً تجريبياً عبر واتساب أو البريد وسنرتب لك جولة على المنصة.',
    keywords: ['تجريبي', 'demo', 'عرض'],
    actions: [
      { id: 'a1', type: 'open_whatsapp', labelAr: 'واتساب', value: DEFAULT_SMART_ASSISTANT_CONTACT.whatsapp },
      { id: 'a2', type: 'open_email', labelAr: 'بريد إلكتروني', value: DEFAULT_SMART_ASSISTANT_CONTACT.email },
    ],
    priority: 85,
    order: 1,
    scopes: LANDING,
    active: true,
  },
  {
    id: 'ans_password',
    categoryId: 'cat_account',
    flowId: 'flow_password',
    titleAr: 'تغيير كلمة المرور',
    bodyAr: 'يمكنك تغيير كلمة المرور:\n1) افتح الإعدادات\n2) اختر الأمان\n3) اضغط تغيير كلمة المرور\n\nإن نسيت كلمة المرور استخدم "نسيت كلمة المرور" من صفحة الدخول.',
    keywords: ['كلمة المرور', 'نسيت السر', 'نسيت الباسورد', 'password', 'password reset', 'باسورد'],
    actions: [
      { id: 'a1', type: 'open_route', labelAr: 'فتح الإعدادات', value: '/login' },
    ],
    priority: 100,
    order: 1,
    scopes: STAFF,
    active: true,
  },
  {
    id: 'ans_account_create',
    categoryId: 'cat_account',
    flowId: 'flow_account_create',
    titleAr: 'إنشاء حساب',
    bodyAr: 'حسابات المدرسة تُنشأ من لوحة مدير المدرسة أو السوبر أدمن حسب الدور. لا تُنشأ حسابات مدرسية تلقائياً من التسجيل العام.',
    keywords: ['إنشاء حساب', 'حساب جديد', 'new account'],
    actions: [],
    priority: 80,
    order: 1,
    scopes: STAFF,
    active: true,
  },
  {
    id: 'ans_profile',
    categoryId: 'cat_account',
    flowId: 'flow_profile',
    titleAr: 'تعديل البيانات',
    bodyAr: 'من لوحة حسابك افتح الإعدادات وحدّث الاسم أو بيانات التواصل المتاحة لدورك.',
    keywords: ['تعديل البيانات', 'الملف الشخصي', 'profile'],
    actions: [],
    priority: 70,
    order: 1,
    scopes: STAFF,
    active: true,
  },
  {
    id: 'ans_login_issue',
    categoryId: 'cat_tech',
    flowId: 'flow_login_issue',
    titleAr: 'تعذّر الدخول',
    bodyAr: 'جرّب: تحديث الصفحة، مسح الكاش، التأكد من الإنترنت، وإعادة المحاولة عبر Google أو البريد. إن استمرت المشكلة اطلب الدعم.',
    keywords: ['لا أستطيع الدخول', 'login', 'تسجيل الدخول', 'خطأ دخول'],
    actions: [
      { id: 'a1', type: 'create_ticket', labelAr: 'طلب دعم بشري', value: 'login_issue' },
    ],
    priority: 88,
    order: 1,
    scopes: ALL,
    active: true,
  },
  {
    id: 'ans_app',
    categoryId: 'cat_tech',
    flowId: 'flow_app',
    titleAr: 'التطبيق',
    bodyAr: 'المنصة تعمل كتطبيق ويب تقدمي (PWA) ويمكن تثبيتها على الجوال. رابط التحميل متوفر في الصفحة الرئيسية عند التفعيل.',
    keywords: ['تطبيق', 'apk', 'جوال', 'pwa', 'تحميل'],
    actions: [
      { id: 'a1', type: 'open_section', labelAr: 'قسم التحميل', value: '#download' },
    ],
    priority: 75,
    order: 1,
    scopes: ALL,
    active: true,
  },
  {
    id: 'ans_students',
    categoryId: 'cat_school',
    flowId: 'flow_students',
    titleAr: 'إدارة الطلاب',
    bodyAr: 'من لوحة المدير افتح تبويب الطلاب لإضافة السجلات، الصفوف، وربط أولياء الأمور.',
    keywords: ['طلاب', 'students', 'إضافة طالب'],
    actions: [],
    priority: 80,
    order: 1,
    scopes: ADMIN,
    active: true,
  },
  {
    id: 'ans_staff',
    categoryId: 'cat_school',
    flowId: 'flow_staff',
    titleAr: 'الموظفين',
    bodyAr: 'من تبويب الكادر أضف المعلمين والموظفين وحدد الأدوار والصلاحيات.',
    keywords: ['موظفين', 'كادر', 'staff', 'معلمين'],
    actions: [],
    priority: 78,
    order: 1,
    scopes: ADMIN,
    active: true,
  },
  {
    id: 'ans_reports',
    categoryId: 'cat_school',
    flowId: 'flow_reports',
    titleAr: 'التقارير',
    bodyAr: 'التقارير المتقدمة متاحة من قائمة التقارير حسب باقة المدرسة.',
    keywords: ['تقارير', 'reports'],
    actions: [],
    priority: 76,
    order: 1,
    scopes: ADMIN,
    active: true,
  },
  {
    id: 'ans_absence',
    categoryId: 'cat_parent',
    flowId: 'flow_absence',
    titleAr: 'الغياب',
    bodyAr: 'تابع غياب أبنائك من تبويب الحضور/الغيابات في تطبيق ولي الأمر.',
    keywords: ['غياب', 'attendance', 'حضور ابني'],
    actions: [],
    priority: 80,
    order: 1,
    scopes: PARENT,
    active: true,
  },
  {
    id: 'ans_fees',
    categoryId: 'cat_parent',
    flowId: 'flow_fees',
    titleAr: 'الرسوم',
    bodyAr: 'الأقساط والمستحقات تظهر في تبويب الرسوم. للتفاصيل تواصل مع إدارة المدرسة.',
    keywords: ['رسوم', 'أقساط', 'tuition', 'fees'],
    actions: [],
    priority: 82,
    order: 1,
    scopes: PARENT,
    active: true,
  },
  {
    id: 'ans_homework',
    categoryId: 'cat_parent',
    flowId: 'flow_homework',
    titleAr: 'الواجبات',
    bodyAr: 'الواجبات تظهر في تبويب الواجبات لكل طالب مرتبط بحسابك.',
    keywords: ['واجبات', 'homework'],
    actions: [],
    priority: 78,
    order: 1,
    scopes: PARENT,
    active: true,
  },
  {
    id: 'ans_grades',
    categoryId: 'cat_teacher',
    flowId: 'flow_grades',
    titleAr: 'الدرجات',
    bodyAr: 'من تبويب الدرجات اختر الصف والمادة ثم أدخل الدرجات واحفظ.',
    keywords: ['درجات', 'grades', 'علامات'],
    actions: [],
    priority: 80,
    order: 1,
    scopes: TEACHER,
    active: true,
  },
  {
    id: 'ans_attendance_t',
    categoryId: 'cat_teacher',
    flowId: 'flow_attendance',
    titleAr: 'الحضور',
    bodyAr: 'سجّل الحضور اليومي من تبويب الحضور للصف المحدد.',
    keywords: ['حضور', 'تسجيل حضور'],
    actions: [],
    priority: 78,
    order: 1,
    scopes: TEACHER,
    active: true,
  },
  {
    id: 'ans_schedule',
    categoryId: 'cat_teacher',
    flowId: 'flow_schedule',
    titleAr: 'الجدول',
    bodyAr: 'جدول الحصص متاح من تبويب الجداول حسب إعدادات المدرسة.',
    keywords: ['جدول', 'schedule'],
    actions: [],
    priority: 76,
    order: 1,
    scopes: TEACHER,
    active: true,
  },
  {
    id: 'ans_commission',
    categoryId: 'cat_distributor',
    flowId: 'flow_commission',
    titleAr: 'العمولات',
    bodyAr: 'عمولاتك تظهر في لوحة الموزع ضمن تبويب العمولات والكوبونات.',
    keywords: ['عمولة', 'عمولات', 'commission'],
    actions: [],
    priority: 80,
    order: 1,
    scopes: DIST,
    active: true,
  },
  {
    id: 'ans_orders',
    categoryId: 'cat_distributor',
    flowId: 'flow_orders',
    titleAr: 'الطلبات',
    bodyAr: 'تابع طلبات الاشتراك المرتبطة بك من لوحة الموزع.',
    keywords: ['طلبات', 'orders'],
    actions: [],
    priority: 78,
    order: 1,
    scopes: DIST,
    active: true,
  },
  {
    id: 'ans_contact',
    categoryId: 'cat_support',
    flowId: 'flow_contact',
    titleAr: 'تواصل معنا',
    bodyAr: 'تواصل عبر واتساب أو البريد. إن لم تجد الحل يمكنك فتح تذكرة دعم من المساعد.',
    keywords: ['تواصل', 'دعم', 'واتساب', 'بريد', 'مساعدة', 'support'],
    actions: [
      { id: 'a1', type: 'open_whatsapp', labelAr: 'واتساب', value: DEFAULT_SMART_ASSISTANT_CONTACT.whatsapp },
      { id: 'a2', type: 'open_email', labelAr: 'بريد', value: DEFAULT_SMART_ASSISTANT_CONTACT.email },
      { id: 'a3', type: 'create_ticket', labelAr: 'لم أجد الحل', value: 'unresolved' },
    ],
    priority: 70,
    order: 1,
    scopes: ALL,
    active: true,
  },
];

export function getSeedCatalog(): AssistantCatalog {
  const answers = SEED_ANSWERS;
  return {
    categories: SEED_CATEGORIES,
    flows: SEED_FLOWS,
    answers,
    keywords: buildKeywordsFromAnswers(answers),
  };
}

/** Compat export for older widget props */
export const LANDING_SEED_RULES: SmartAssistantRule[] = SEED_ANSWERS.map((a) => ({
  id: a.id,
  scope: a.scopes.length === 1 ? a.scopes[0] : a.scopes,
  keywords: a.keywords,
  response: a.bodyAr,
  priority: a.priority,
  active: a.active,
  actions: a.actions
    .filter((x) => ['open_section', 'open_whatsapp', 'open_email'].includes(x.type))
    .map((x) => ({ type: x.type as 'open_section' | 'open_whatsapp' | 'open_email', value: x.value })),
}));
