FROM node:20-slim
WORKDIR /app
COPY package*.json ./
COPY .npmrc ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npx esbuild server.ts --bundle --platform=node --format=esm --packages=external --outfile=dist/server.mjs
ENV PORT=8080
EXPOSE 8080
CMD ["node", "dist/server.mjs"]